doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        url: "%env(resolve:DATABASE_URL)%"
      batch:
        url: "%env(resolve:DATABASE_URL_BATCH)%"

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  # orm:
  #   auto_generate_proxy_classes: true
  #   naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
  #   auto_mapping: true
  #   mappings:
  #     App:
  #       is_bundle: false
  #       type: annotation
  #       dir: "%kernel.project_dir%/src/Entity"
  #       prefix: 'App\Entity'
  #       alias: App

  orm:
    default_entity_manager: default
    auto_generate_proxy_classes: true
    entity_managers:
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
          App:
            is_bundle: false
            type: annotation
            dir: "%kernel.project_dir%/src/Entity"
            prefix: 'App\Entity'
            alias: App
      batch:
        connection: batch
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
          App:
            is_bundle: false
            type: annotation
            dir: "%kernel.project_dir%/src/Entity"
            prefix: 'App\Entity'
            alias: App
